// <auto-generated />
namespace WeatherDemoWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PopulateDb2Try : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulateDb2Try));
        
        string IMigrationMetadata.Id
        {
            get { return "202101231429486_PopulateDb2Try"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
